# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a269d7af48505dacfb6b92b6a98bbaa24a1e03de3fde0374dcf39ca1e46d5e0cd3a6cf252ef2e76bd49e4c5ed1c8186d8fcd563a51d0f6450f74a651030705c9

test:
  secret_key_base: 5de935c001b9ef45421c1ea00e737094d06da02dc8409007e00c57a7626e3ae62bf9c8c6c8a3fb0b04cf86042033b500189b7fbac5f4b1e6f47822a11d28a2fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
